### ISSUE TITLE
Deciding on a framework

### ISSUE THREAD

**Issue by ErikBjare** [ActivityWatch/aw-traygui#1]
We need a tray icon, and I currently have four options where I need to choose one, a critical decision. 

Options:

 - Written in Python
   - With GTK
   - With QT
 - Written in JavaScript/Node.js
    - With Electron
    - With NW.js (formerly node-webkit)

**Comment by johan-bjareholt** [comment]
Have we fully decided to use Qt?
I think that's the best option.
